### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MarcelHekkert** [kathamo/Kathamo#1]
Will there be documentation for all available classes to use? Also, adding less/sass files for seperation of specific elements would be great.

**Comment by debashisbarman** [comment]
The documentation is available for both versions of Kathamo. For Kathamo 2.0.0, the documentation part is in "README.md" file and for Kathamo 3.0.0, documentation (with example) is provided in the "demo.html". You can also refer to http://www.debashisbarman.in/2015/04/03/Kathamo-Means-Framework.html for documentation.

Regarding less/sass files, I am also planning to add. Soon I will be adding those files.

Thank you.

**Comment by MarcelHekkert** [comment]
Great! I will be watching this repo.

**Comment by debashisbarman** [comment]
Glad to hear that! Thanks.
